apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::ACCOUND_ID:role/APP_NAME-iam-node-groups
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::ACCOUND_ID:role/SSO_ROLE
      username: SSO_USERNAME
      groups:
        - system:masters 
    - rolearn: arn:aws:sts::ACCOUND_ID:assumed-role/SSO_ROLE
      username: SSO_USERNAME
      groups:
        - system:masters
    - rolearn: arn:aws:iam::ACCOUND_ID:role/Developers
      username: Developers
      groups:
        - system:masters
    - rolearn: arn:aws:iam::ACCOUND_ID:role/DevelopersAdmin
      username: DevelopersAdmin
      groups:
        - system:masters 
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system